SUPABASE_URL = https://pxdagtmtkfomasiokide.supabase.co
SUPABASE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZGFndG10a2ZvbWFzaW9raWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NzQ1MzYsImV4cCI6MjA1ODA1MDUzNn0.eXN1yqooRzJXCFMguiSGVF5nAsuI9-Gl2uO2evpM4OQ
